# Generated by Django 6.0.2 on 2026-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Userxxx',
                'verbose_name_plural': 'Userxxxs',
                'db_table': 'user',
                'ordering': ['age'],
                'indexes': [models.Index(fields=['name'], name='user_name_969ffe_idx')],
            },
        ),
    ]
