# Generated by Django 6.0.2 on 2026-03-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'verbose_name': 'Userxxx', 'verbose_name_plural': 'Userxxxs'},
        ),
    ]
