# Generated by Django 6.0.2 on 2026-03-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models_training', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
    ]
