# Generated by Django 6.0.2 on 2026-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models_training', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='product_name_c4c985_idx')],
            },
        ),
    ]
