# Generated by Django 6.0.2 on 2026-03-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models_training', '0004_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slug'),
        ),
    ]
