# Generated by Django 6.0.2 on 2026-03-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models_training', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ayoub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ayoub',
                'ordering': ['-name'],
            },
        ),
    ]
