# Generated by Django 6.0.2 on 2026-03-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="image",
        ),
    ]
