# Generated by Django 6.0.2 on 2026-03-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relation", "0002_remove_categories_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="description",
        ),
    ]
