# Generated by Django 6.0.2 on 2026-03-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relation", "0003_remove_products_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="courses", to="relation.student"
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.DeleteModel(
            name="Categories",
        ),
        migrations.DeleteModel(
            name="Products",
        ),
    ]
