# Generated by Django 6.0.2 on 2026-03-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
