run:
	@python manage.py runserver
migrate:
	@python manage.py makemigrations
	@python manage.py migrate
createsuperuser:
	@python manage.py createsuperuser

test:
	@python manage.py test

install:
	@pip install -r requirements.txt

app:
	@python manage.py startapp $(name)