# Generated by Django 6.0.2 on 2026-02-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_marke_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.DeleteModel(
            name='etudian',
        ),
        migrations.DeleteModel(
            name='students',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='marke',
        ),
    ]
